spring.data.mongodb.uri=mongodb+srv://kush:kush2025@cluster0.dq4nxrr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
